### ISSUE TITLE
'montage' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by alexykouakou** [emgag/video-thumbnail-sprite#3]
I use Php-ffmpeg with laravel.
ImageMagick is istalled.
But I get this error:
'montage' is not recognized as an internal or external command,
operable program or batch file.

How can I solve it?
my system is Windows 10

**Comment by maetthu** [comment]
I don't have Windows to test it atm, but as _montage_ is called as is, w/o a path, make sure the PATH environment variable contains the path to the ImageMagick installation. Can you run _montage_ on the command prompt?

**Comment by maetthu** [comment]
Hmm, I didn't know that the command name is different in Windows.

Does it work if you change the command to _magick montage_ in
https://github.com/emgag/video-thumbnail-sprite/blob/master/src/ThumbnailSprite.php#L312 ? If yes, I'll add an option to set a custom command name.

**Comment by alexykouakou** [comment]
ok good! In ThumbnailSprite.php, _magick montage_ works. 
But I get an another error:
_montage: unable to open image 'C:\wamp\www\7-playd\LARAVEL\thirdInstall\public/sprite/sprite.jpg': No such file or directory @ error/blob.c/OpenBlob/3146._

**Comment by maetthu** [comment]
Can you output the value of the $cmd variable before [this line](https://github.com/emgag/video-thumbnail-sprite/blob/master/src/ThumbnailSprite.php#L320) and check if you can run this command on the prompt? if not, try changing / to \\. I'll try to get hold of a Windows 10 environment to test, but it'll take a while.

**Comment by alexykouakou** [comment]
I put a default image "sprite.jpg" in public/sprite and excuted the cmd. The default is overrided and I have now two files, a new generated sprite and a vtt file.
so I am required to specify a default image before generated sprite. this is not a problem for me, but is this normal?

**Comment by maetthu** [comment]
No, montage should create sprite.jpg, it isn't necessary that it exists beforehand. Maybe the Windows version behaves differently? this would be unfortunate. Or maybe, your webserver didn't have permissions to create the file, but could overwrite the one you created manually? Though that would probably mean that it shouldn't be able to create the vtt file as well.

**Comment by alexykouakou** [comment]
Ok problem solve! I changed permissions.
All works fine! thanks for the assistance!

**Comment by maetthu** [comment]
You're welcome :smile: 

I'll add an option to overwrite the _montage_ command soon-ish.
