### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by kfeng0806** [emgag/video-thumbnail-sprite#6]
Reference to https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/210
FFprobe can't find binary file
```
Alchemy\BinaryDriver\Exception\ExecutableNotFoundException
Executable not found, proposed : avprobe, ffprobe
```

**Comment by maetthu** [comment]
video-thumbnail-sprite and php-ffmpeg just run the "ffmpeg" and "ffprobe" binary without an absolute path. Make sure these commands are installed and the installation directory is present in your $PATH environment variable.
